version: 1.2
workflows:
   - subclass: NFL
     primaryDescriptorPath: /strepA.config
     name: strepA-nf
     authors:
      - name: Scott Hazelhurst
        email: scott.hazelhurst@wits.ac.za
        orcid: 0000-0002-0581-149X 
     publish: True
   - subclass: NFL
     primaryDescriptorPath: /strepB.config
     name: strepB-nf
     authors:
      - name: Scott Hazelhurst
        email: scott.hazelhurst@wits.ac.za
        orcid: 0000-0002-0581-149X 
     publish: True
   - subclass: NFL
     primaryDescriptorPath: /spn.config
     name: spn-nf
     authors:
      - name: Scott Hazelhurst
        email: scott.hazelhurst@wits.ac.za
        orcid: 0000-0002-0581-149X 
     publish: True
